---
name: checks

on: [push]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test
        run: pytest